version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
